'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class VisitorView
    
    '''<summary>
    '''VisViewerGV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VisViewerGV As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''VisitorsDetailDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VisitorsDetailDS As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''RelationDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RelationDS As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''CountryDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CountryDS As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''InmateVisitorViewDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InmateVisitorViewDS As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''EthnicDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EthnicDS As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''GenderDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GenderDS As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''LocationDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LocationDS As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''CStatusDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CStatusDS As Global.System.Web.UI.WebControls.SqlDataSource
End Class
